name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: "1"
  UV_CONSTRAINT: "${{ github.workspace }}/.github/constraints.txt"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # for codecov oidc
    strategy:
      matrix:
        include:
        - { python: "3.12", feats: full }
        - { python: "3.14", feats: min }
        - { python: "3.14", feats: full }
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          filter: blob:none
          persist-credentials: false
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0
        with:
          python-version: ${{ matrix.python }}
      - run: uv tool install hatch
      - run: hatch -v env create hatch-test.py${{ matrix.python }}-${{ matrix.feats }}
      - run: hatch test --cover --python=${{ matrix.python }} -i feature-set=${{ matrix.feats }}
      - run: hatch env run --env hatch-test.py${{ matrix.python }}-${{ matrix.feats }} -- coverage xml
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: coverage.xml
          use_oidc: true
  check:
    if: always()
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
